ansible_host: <ip-adress>
install_drive: /dev/nvme0n1p
boot_partition_suffix: 5
root_partition_suffix: 6
hostname: Lasse-Laptop
dual_boot_efi: true
intel: true
bluetooth: true
sshd: true
xorg: true
plasma: true
